sonar.projectName=FinTrack CI/CD
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.php.coverage.reportPaths=backend/coverage.xml
sonar.exclusions=backend/vendor/**,frontend/node_modules/**,frontend/dist/**
sonar.coverage.exclusions=frontend/src/main.jsx,frontend/vite.config.js
sonar.sourceEncoding=UTF-8
